name: Test codes
on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:
jobs:
  Test:
    name: Run test codes
    if: |
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: npm ci

      - name: Run vitest
        run: npm run test:coverage

      - name: Show coverage report
        uses: davelosert/vitest-coverage-report-action@v2
